import type { QuizQuestion, QuizQuestionId } from "../domain/quiz.types";

export const quizQuestions = [
  {
    id: "perception",
    block: "Identificação",
    eyebrow: "Pergunta 1 de 12",
    prompt: "O que mais chama sua atenção quando você olha para o seu corpo hoje?",
    hint: "Não é sobre julgar o seu corpo. É sobre nomear o que vem ocupando espaço demais.",
    presentation: "scenario",
    autoAdvance: true,
    options: [
      { id: "cellulite", label: "A celulite e as ondulações da pele.", detail: "Principalmente em coxas, glúteos ou quadril." },
      { id: "firmness", label: "A flacidez e a perda de firmeza.", detail: "A pele parece diferente de como eu gostaria." },
      { id: "contour", label: "O contorno de algumas regiões.", detail: "A roupa marca e eu reparo imediatamente." },
      { id: "balanced", label: "Um pouco de tudo isso.", detail: "Não existe um único ponto: é o conjunto." },
    ],
  },
  {
    id: "first-thought",
    block: "Identificação",
    eyebrow: "Pergunta 2 de 12",
    prompt: "Quando você percebe isso, qual frase passa pela sua cabeça — mesmo que você não diga em voz alta?",
    presentation: "sentence",
    autoAdvance: true,
    options: [
      { id: "later", label: "“Depois eu resolvo isso.”", detail: "Eu adio para não ter de lidar com isso agora.", narrative: { recoveryCapacity: -1 } },
      { id: "care-again", label: "“Eu me deixei por último de novo.”", detail: "Sinto falta de voltar a me escolher.", narrative: { actionBias: 2 } },
      { id: "should-not-care", label: "“Eu nem deveria ligar tanto para isso.”", detail: "Mas ainda assim, mexe comigo.", narrative: { clarityNeed: 1 } },
      { id: "tried-a-lot", label: "“Já tentei tanta coisa… por que seria diferente?”", detail: "Quero acreditar, mas tenho medo de me frustrar.", narrative: { proofNeed: 2 } },
    ],
  },
  {
    id: "situation-weight",
    block: "Identificação",
    eyebrow: "Pergunta 3 de 12",
    prompt: "Em qual momento esse incômodo rouba mais a sua liberdade?",
    hint: "Pense naquela situação em que você muda o que faria por causa do que viu.",
    presentation: "scenario",
    autoAdvance: true,
    options: [
      { id: "beach", label: "Na praia ou piscina.", detail: "Quero relaxar, mas fico calculando como o corpo aparece." },
      { id: "getting-dressed", label: "Na hora de me vestir.", detail: "A roupa deixa de ser escolha e vira esconderijo." },
      { id: "photos", label: "Em fotos.", detail: "Eu penso no ângulo antes de viver o momento." },
      { id: "comparison", label: "Quando me comparo com outras mulheres.", detail: "O meu corpo parece sempre perder nessa comparação.", narrative: { clarityNeed: 1 } },
    ],
  },
  {
    id: "reaction",
    block: "Rotina",
    eyebrow: "Pergunta 4 de 12",
    prompt: "E o que você faz logo depois, quase no automático?",
    presentation: "scenario",
    autoAdvance: true,
    options: [
      { id: "change-clothes", label: "Troco de roupa até me sentir escondida o bastante." },
      { id: "rethink-going-out", label: "Penso duas vezes antes de sair — às vezes desisto." },
      { id: "ignore", label: "Finjo que não me afetou e sigo o dia." },
      { id: "promise-care", label: "Faço mais uma promessa de que vou começar a me cuidar.", narrative: { actionBias: 1 } },
    ],
  },
  {
    id: "avoidance",
    block: "Rotina",
    eyebrow: "Pergunta 5 de 12",
    prompt: "Quanto isso já interferiu em algo que você queria vestir, registrar ou viver?",
    presentation: "compact",
    autoAdvance: true,
    options: [
      { id: "yes", label: "Mais vezes do que eu gostaria de admitir." },
      { id: "sometimes", label: "Algumas vezes — e eu lembro delas." },
      { id: "rarely", label: "Raramente, mas o incômodo existe." },
      { id: "never", label: "Nunca deixei de fazer, mas penso nisso." },
    ],
  },
  {
    id: "deepest-impact",
    block: "Rotina",
    eyebrow: "Pergunta 6 de 12",
    prompt: "Se você for completamente honesta: qual é a ferida por trás do incômodo?",
    presentation: "sentence",
    autoAdvance: true,
    options: [
      { id: "appearance", label: "Não gostar do que vejo, mesmo tentando não ligar." },
      { id: "confidence", label: "Sentir minha confiança diminuir em momentos que deveriam ser leves." },
      { id: "routine", label: "Me culpar por nunca conseguir manter uma rotina.", narrative: { structurePreference: 2 } },
      { id: "nothing-works", label: "Ter a sensação de que nada funciona para mim.", narrative: { proofNeed: 2 } },
    ],
  },
  {
    id: "restart-trigger",
    block: "Rotina",
    eyebrow: "Pergunta 7 de 12",
    prompt: "O que normalmente precisa doer para você decidir recomeçar?",
    presentation: "sentence",
    autoAdvance: true,
    options: [
      { id: "motivated", label: "Eu me canso de adiar e sinto um impulso de mudança." },
      { id: "saw-photo", label: "Vejo uma foto e ela mexe comigo pelo resto do dia." },
      { id: "clothes-fit", label: "Uma roupa não veste como eu queria — e isso me derruba." },
      { id: "promise-different", label: "Percebo que quebrei mais uma promessa feita a mim mesma.", narrative: { recoveryCapacity: 1 } },
    ],
  },
  {
    id: "history",
    block: "Histórico",
    eyebrow: "Pergunta 8 de 12",
    prompt: "Qual dessas histórias você está mais cansada de repetir?",
    presentation: "sentence",
    autoAdvance: true,
    options: [
      { id: "start-stop", label: "Começo cheia de vontade e me vejo parando outra vez.", narrative: { recoveryCapacity: 2 } },
      { id: "research", label: "Pesquiso tanto que termino mais confusa do que comecei.", narrative: { clarityNeed: 2 } },
      { id: "disappointed", label: "Já gastei dinheiro, criei expectativa e me decepcionei.", narrative: { proofNeed: 3 } },
      { id: "still-looking", label: "Continuo procurando algo que faça sentido para a minha vida real.", narrative: { clarityNeed: 1, proofNeed: 1 } },
    ],
  },
  {
    id: "dropoff",
    block: "Histórico",
    eyebrow: "Pergunta 9 de 12",
    prompt: "Em que ponto o cuidado costuma escapar das suas mãos?",
    presentation: "scenario",
    autoAdvance: true,
    options: [
      { id: "time", label: "Quando a semana aperta, eu me deixo por último.", narrative: { structurePreference: 2 } },
      { id: "forget", label: "Eu esqueço por alguns dias e sinto que perdi tudo.", narrative: { structurePreference: 2 } },
      { id: "slow-results", label: "A ansiedade por perceber mudança vence a constância.", narrative: { proofNeed: 1 } },
      { id: "routine-change", label: "Um imprevisto quebra o ritmo e eu não consigo voltar.", narrative: { recoveryCapacity: 2 } },
    ],
  },
  {
    id: "decision-weight",
    block: "Histórico",
    eyebrow: "Pergunta 10 de 12",
    prompt: "O que uma nova tentativa precisa respeitar para merecer a sua confiança?",
    presentation: "sentence",
    autoAdvance: true,
    options: [
      { id: "money", label: "Meu dinheiro — não quero pagar por mais uma frustração.", narrative: { clarityNeed: 2 } },
      { id: "expectation", label: "Meu emocional — não quero me iludir de novo.", narrative: { proofNeed: 2 } },
      { id: "simple", label: "Minha rotina — se for complicado, não vai durar.", narrative: { actionBias: 2 } },
      { id: "a-path", label: "Minha necessidade de enxergar um caminho possível.", narrative: { structurePreference: 2 } },
    ],
  },
  {
    id: "future-scene",
    block: "Futuro",
    eyebrow: "Pergunta 11 de 12",
    prompt: "Imagine que esse incômodo já não decide por você. O que você recupera primeiro?",
    presentation: "scenario",
    autoAdvance: true,
    options: [
      { id: "saved-clothes", label: "A liberdade de usar aquela roupa sem me esconder." },
      { id: "easy-photos", label: "A espontaneidade de tirar fotos sem procurar defeitos." },
      { id: "calm-beach", label: "A tranquilidade de ir à praia e estar presente de verdade." },
      { id: "lighter", label: "A leveza de olhar para mim sem começar uma cobrança." },
    ],
  },
  {
    id: "future-goal",
    block: "Futuro",
    eyebrow: "Pergunta 12 de 12",
    prompt: "No fundo, qual transformação você quer levar para fora do espelho?",
    presentation: "sentence",
    autoAdvance: true,
    options: [
      { id: "trust", label: "Quero voltar a me sentir segura dentro do meu próprio corpo." },
      { id: "lasting-routine", label: "Quero provar para mim que consigo sustentar um cuidado.", narrative: { structurePreference: 3 } },
      { id: "simple-care", label: "Quero me escolher todos os dias sem transformar isso em peso.", narrative: { actionBias: 2 } },
      { id: "stop-restarting", label: "Quero parar de colecionar recomeços e construir continuidade.", narrative: { recoveryCapacity: 3 } },
    ],
  },
] as const satisfies readonly QuizQuestion[];

export const quizQuestionMap = Object.fromEntries(
  quizQuestions.map((question) => [question.id, question]),
) as unknown as Readonly<Record<QuizQuestionId, QuizQuestion>>;

export function getQuizOption(questionId: QuizQuestionId, optionId: string): QuizQuestion["options"][number] | null {
  return quizQuestionMap[questionId].options.find((option) => option.id === optionId) ?? null;
}
