import type { QuizQuestion, QuizQuestionId } from "../domain/quiz.types";

export const quizQuestions = [
  {
    id: "perception",
    block: "Identificação",
    eyebrow: "Sobre o que você percebe",
    prompt: "Quando você percebe mais a celulite?",
    presentation: "scenario",
    autoAdvance: true,
    options: [
      { id: "outfit", label: "Quando experimento uma roupa." },
      { id: "photo", label: "Quando vejo uma foto minha." },
      { id: "bikini", label: "Quando coloco um biquíni ou short." },
      { id: "mirror", label: "Quando me olho no espelho antes de sair." },
    ],
  },
  {
    id: "first-thought",
    block: "Identificação",
    eyebrow: "Sobre o que você percebe",
    prompt: "Qual pensamento costuma aparecer primeiro?",
    presentation: "sentence",
    autoAdvance: true,
    options: [
      { id: "later", label: "“Depois eu resolvo isso.”", narrative: { recoveryCapacity: -1 } },
      { id: "care-again", label: "“Preciso voltar a cuidar de mim.”", narrative: { actionBias: 2 } },
      { id: "should-not-care", label: "“Nem deveria ligar para isso.”", narrative: { clarityNeed: 1 } },
      { id: "tried-a-lot", label: "“Já tentei tanta coisa...”", narrative: { proofNeed: 2 } },
    ],
  },
  {
    id: "situation-weight",
    block: "Identificação",
    eyebrow: "Sobre o que você percebe",
    prompt: "Em qual situação isso pesa mais?",
    presentation: "scenario",
    autoAdvance: true,
    options: [
      { id: "beach", label: "Na praia ou piscina." },
      { id: "getting-dressed", label: "Na hora de me vestir." },
      { id: "photos", label: "Em fotos." },
      { id: "comparison", label: "Quando comparo meu corpo com outras mulheres.", narrative: { clarityNeed: 1 } },
    ],
  },
  {
    id: "reaction",
    block: "Rotina",
    eyebrow: "Sobre a sua rotina",
    prompt: "Quando isso acontece, qual costuma ser sua reação?",
    presentation: "scenario",
    autoAdvance: true,
    options: [
      { id: "change-clothes", label: "Troco de roupa." },
      { id: "rethink-going-out", label: "Penso duas vezes antes de sair." },
      { id: "ignore", label: "Tento ignorar." },
      { id: "promise-care", label: "Prometo que vou começar a me cuidar.", narrative: { actionBias: 1 } },
    ],
  },
  {
    id: "avoidance",
    block: "Rotina",
    eyebrow: "Sobre a sua rotina",
    prompt: "Você já deixou de fazer alguma coisa por causa disso?",
    presentation: "compact",
    autoAdvance: true,
    options: [
      { id: "yes", label: "Sim." },
      { id: "sometimes", label: "Algumas vezes." },
      { id: "rarely", label: "Raramente." },
      { id: "never", label: "Nunca." },
    ],
  },
  {
    id: "deepest-impact",
    block: "Rotina",
    eyebrow: "Sobre a sua rotina",
    prompt: "O que mais incomoda?",
    presentation: "sentence",
    autoAdvance: true,
    options: [
      { id: "appearance", label: "A aparência." },
      { id: "confidence", label: "A sensação de perder a confiança." },
      { id: "routine", label: "Não conseguir manter uma rotina.", narrative: { structurePreference: 2 } },
      { id: "nothing-works", label: "Sentir que nada funciona.", narrative: { proofNeed: 2 } },
    ],
  },
  {
    id: "restart-trigger",
    block: "Rotina",
    eyebrow: "Sobre a sua rotina",
    prompt: "Quando você decide começar novamente, normalmente acontece porque...",
    presentation: "sentence",
    autoAdvance: true,
    options: [
      { id: "motivated", label: "Me senti motivada." },
      { id: "saw-photo", label: "Vi alguma foto minha." },
      { id: "clothes-fit", label: "Uma roupa deixou de servir como eu queria." },
      { id: "promise-different", label: "Prometi a mim mesma que, dessa vez, seria diferente.", narrative: { recoveryCapacity: 1 } },
    ],
  },
  {
    id: "history",
    block: "Histórico",
    eyebrow: "Sobre o que você já tentou",
    prompt: "Qual dessas frases mais parece com você?",
    presentation: "sentence",
    autoAdvance: true,
    options: [
      { id: "start-stop", label: "Começo animada e paro depois.", narrative: { recoveryCapacity: 2 } },
      { id: "research", label: "Pesquiso muito antes de comprar qualquer coisa.", narrative: { clarityNeed: 2 } },
      { id: "disappointed", label: "Já investi em produtos que não atenderam às expectativas.", narrative: { proofNeed: 3 } },
      { id: "still-looking", label: "Ainda estou procurando algo que faça sentido.", narrative: { clarityNeed: 1, proofNeed: 1 } },
    ],
  },
  {
    id: "dropoff",
    block: "Histórico",
    eyebrow: "Sobre o que você já tentou",
    prompt: "O que normalmente faz você desistir?",
    presentation: "scenario",
    autoAdvance: true,
    options: [
      { id: "time", label: "Falta de tempo.", narrative: { structurePreference: 2 } },
      { id: "forget", label: "Esqueço.", narrative: { structurePreference: 2 } },
      { id: "slow-results", label: "Não vejo resultados rápidos.", narrative: { proofNeed: 1 } },
      { id: "routine-change", label: "A rotina muda completamente.", narrative: { recoveryCapacity: 2 } },
    ],
  },
  {
    id: "decision-weight",
    block: "Histórico",
    eyebrow: "Sobre o que você já tentou",
    prompt: "Quando você pensa em voltar a se cuidar, o que mais pesa?",
    presentation: "sentence",
    autoAdvance: true,
    options: [
      { id: "money", label: "Não quero desperdiçar dinheiro.", narrative: { clarityNeed: 2 } },
      { id: "expectation", label: "Tenho medo de criar expectativa.", narrative: { proofNeed: 2 } },
      { id: "simple", label: "Quero algo simples.", narrative: { actionBias: 2 } },
      { id: "a-path", label: "Quero sentir que finalmente encontrei um caminho.", narrative: { structurePreference: 2 } },
    ],
  },
  {
    id: "future-scene",
    block: "Futuro",
    eyebrow: "Sobre o que você deseja",
    prompt: "Se daqui a alguns meses você percebesse uma melhora, qual seria a primeira coisa que faria?",
    presentation: "scenario",
    autoAdvance: true,
    options: [
      { id: "saved-clothes", label: "Usaria aquela roupa guardada." },
      { id: "easy-photos", label: "Tiraria fotos sem pensar tanto." },
      { id: "calm-beach", label: "Iria à praia mais tranquila." },
      { id: "lighter", label: "Simplesmente me sentiria mais leve comigo mesma." },
    ],
  },
  {
    id: "future-goal",
    block: "Futuro",
    eyebrow: "Sobre o que você deseja",
    prompt: "Qual dessas frases representa melhor o que você procura hoje?",
    presentation: "sentence",
    autoAdvance: true,
    options: [
      { id: "trust", label: "Quero voltar a confiar em mim." },
      { id: "lasting-routine", label: "Quero criar uma rotina que eu consiga manter.", narrative: { structurePreference: 3 } },
      { id: "simple-care", label: "Quero cuidar de mim sem complicação.", narrative: { actionBias: 2 } },
      { id: "stop-restarting", label: "Quero finalmente parar de recomeçar.", narrative: { recoveryCapacity: 3 } },
    ],
  },
] as const satisfies readonly QuizQuestion[];

export const quizQuestionMap = Object.fromEntries(
  quizQuestions.map((question) => [question.id, question]),
) as unknown as Readonly<Record<QuizQuestionId, QuizQuestion>>;

export function getQuizOption(questionId: QuizQuestionId, optionId: string): QuizQuestion["options"][number] | null {
  return quizQuestionMap[questionId].options.find((option) => option.id === optionId) ?? null;
}
